Repository laradock/laradock, pull requests merged in 2019-12, with the labels that each got.

#2343 Add CHANGE_SOURCE option for php-worker
  docker-compose.yml
  php-worker/Dockerfile
Labels: GFW

#2388 Improve user experience in China
  docker-compose.yml
  env-example
  workspace/Dockerfile
  workspace/sources.sh
Labels: GFW

#2276 Added support for OCI8 extension in workspace and php-fpm containers.
  docker-compose.yml
  env-example
  php-fpm/Dockerfile
  workspace/Dockerfile
Labels: Status: Pending, Type: Enhancement

#2424 chore(php-fpm): update the default locale setting.
  DOCUMENTATION/content/documentation/index.md
  docker-compose.yml
  env-example
  php-fpm/Dockerfile
Labels: Type: Enhancement

#2437 Laravel Horizon PHP 7.4 - fix package oniguruma require
  laravel-horizon/Dockerfile
Labels: Type: Bug Fix

#2452 fix build-args INSTALL_GHOSTSCRIPT were not consumed
  php-worker/Dockerfile
Labels: Type: Bug Fix
